

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
// 
// Do not make changes directly to this file - edit the template instead.
// 
// The following connection settings were used to generate this file:
//     Configuration file:     "Playground.Infrastructure\App.config"
//     Connection String Name: "NServiceBusPlaygroundDbContext"
//     Connection String:      "Data Source=.\LOCALDEVELOPER; Initial Catalog=NServiceBusPlayground; User Id=NServiceBusMaster; password=**zapped**;"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Developer Edition (64-bit)
// Database Engine Edition: Enterprise

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Playground.Infrastructure.Database.Entities
{


    // ************************************************************************
    // POCO classes

    // Account
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.2.0")]
    public class Account
    {
        public int AccountId { get; set; } // AccountId (Primary key)
        public System.DateTime CreateDate { get; set; } // CreateDate
        public System.DateTime? ModifiedDate { get; set; } // ModifiedDate
        public string DisplayName { get; set; } // DisplayName (length: 50)
        public string Email { get; set; } // Email (length: 50)
        public byte Status { get; set; } // Status

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<ApplicationRegistry> ApplicationRegistries { get; set; } // ApplicationRegistry.FK__Applicati__Accou__35BCFE0A

        public Account()
        {
            Status = 0;
            ApplicationRegistries = new System.Collections.Generic.List<ApplicationRegistry>();
        }
    }

    // ApplicationRegistry
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.2.0")]
    public class ApplicationRegistry
    {
        public int Id { get; set; } // Id (Primary key)
        public string ApplicationKey { get; set; } // ApplicationKey (length: 50)
        public System.DateTime CreateDate { get; set; } // CreateDate
        public System.DateTime? ModifiedDate { get; set; } // ModifiedDate
        public string Description { get; set; } // Description (length: 50)
        public byte ApplicationType { get; set; } // ApplicationType
        public int AccountId { get; set; } // AccountId

        // Foreign keys
        public virtual Account Account { get; set; } // FK__Applicati__Accou__35BCFE0A

        public ApplicationRegistry()
        {
            Description = "My New Application";
        }
    }

}
// </auto-generated>

